### PR TITLE
Possible fix for issue #23

### PR DESCRIPTION
**Pull request by CTMarius**
Hi Asbjørn, I'm not sure what the process is for contributing for you project, or even if that is appreciated. As you have might have noticed, I reported a somewhat trivial issue recently, requesting a increased visibility of the board and the solution. Given that the problem is trivial, I thought the solution should be the same, and I went on to implement it. My proposed solution is to make the modal window draggable, thus allowing me to move it to the side of the board and compare the solution with the variants or the board and replay the positions in my mind.  For this I used react-draggable: https://www.npmjs.com/package/react-draggable
Screen caps of the problem and solution:
https://ibb.co/Km9Hjw2
https://ibb.co/nMC6C5B

Apologies if I'm overstepping, feel free to reject the issue/pr if it feels trivial or not worth implementing. In the end just want to mention that I really like this project, it's an awesome idea and I play it daily.

Marius

### CODE REVIEW

**Comment by CTMarius** [comment]
Just noticed that my proposed solution introduced a bug in mobile:

**Comment by CTMarius** [comment]
It seems there's a pre-existing mobile issue on main as well: the contents are not fully displayed and the modal is not scrollable. I'm not sure what the scope is foe mobile but by the looks of it this PR is making a pre-exisring bug worse.

**Comment by Assios** [comment]
Hi! Yeah, I also tested it on mobile, and it seems hard to scroll and close the modal with this addition. Appreciate the PR, though, and this would have been a good fix if it didn't break on mobile.

**Comment by Assios** [comment]
Closing because of the mobile bug.

**Pull request closed without merging**
